# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc3d233b646281c719724d83ee83d6870bd083422cf9cdcb0f9fc2e2c251e59df89bad8bf9f67d02551a4543b2b02f2f92f5a5fae43d9bb61c468c423055ff89

test:
  secret_key_base: 875096869e64846c72bd0e54f130b92c4a41551bd89bbaa392ce4bf46bebcad52aa491182ade23def14de05ab9952e153924924680912a1a1610d591b9616781

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
